---
- name: Create or destroy EC2 instance for hosting
  ec2:
    assign_public_ip: yes
    key_name: "{{ ec2_key_name }}"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_types['rhel7'].size }}"
    image: "{{ ec2_instance_types['rhel7'].ami_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ ec2_exact_count }}"
    count_tag:
      Name: "{{ ec2_name_prefix }}-hosting"
    instance_tags:
      Name: "{{ ec2_name_prefix }}-hosting"
      app: "{{ ec2_name_prefix }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id | default(omit) }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_instance_types['rhel7'].disk_space }}"
        delete_on_termination: true
  register: instance
  tags:
    - always
    - provision
    - hosting