- name: Create EC2 security group
  ec2_group:
    name: insecure_all
    description: all ports open
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    rules:
      - proto: all
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: ec2_exact_count >= 1
  tags:
    - always
    - provision

- import_tasks: "ec2.yml"
  when: ansible_version.full | version_compare('2.4', '>=')

- include: "ec2_async.yml"
  when: ansible_version.full | version_compare('2.4', '<')

- name: Include tasks only needed when creating instances
  include: create.yml
  static: no
  when: ec2_exact_count >= 1
  tags:
    - provision
