- name: Send email to instructor with inventroy attached
  delegate_to: localhost
  sendgrid:
    username: "{{ sendgrid_user | default(omit) }}"
    password: "{{ sendgrid_pass | default(omit) }}"
    api_key: "{{ sendgrid_api_key | default(omit) }}"
    subject: "[Ansible] Important Training Details"
    body: |
          Attached is the Ansible inventory to be used for training.<br>
          Please check your ability to connect to each of the hosts via ssh.<br>

    to_addresses: "{{ instructor_email }}"
    html_body: yes
    from_address: "{{ instructor_email }}"
    attachments:
      - "instructor_inventory.txt"
      - "index.html"
  when: email and instructor_email is defined
  tags:
    - email
