- name: restart ssh
  service:
    name: "{{ common_ssh_service_name }}"
    state: restarted

- name: reboot system
  shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for instance
  delegate_to: localhost
  become: no
  wait_for:
    port: "{{ ssh_port }}"
    host: "{{ ansible_host }}"
    search_regex: OpenSSH
    timeout: 500
    delay: 40
