- debug: msg="{{ hostvars[inventory_hostname] }}"

- debug: msg="{{ username }}"
  ignore_errors: yes

- name: Create User Group
  group:
    name: "{{ username }}"
    state: present
  tags:
    - user_accounts
    - users

- name: Create User Account
  user:
    createhome: yes
    group: "{{ username }}"
    name: "{{ username }}"
    shell: /bin/bash
    state: present
    password: "{{ admin_password_hash }}"
  tags:
    - user_accounts
    - users
